export const DEFAULT_AVATAR =
  'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/f2664fbe-b0bd-454c-bfe6-6e930a07fc49/dflqfd2-0546c20a-4140-496f-aa30-f9b711c02537.jpg/v1/fill/w_894,h_894,q_70,strp/fantasy_character_art_by_midjourney_by_marcelosilvaart_dflqfd2-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTI4MCIsInBhdGgiOiJcL2ZcL2YyNjY0ZmJlLWIwYmQtNDU0Yy1iZmU2LTZlOTMwYTA3ZmM0OVwvZGZscWZkMi0wNTQ2YzIwYS00MTQwLTQ5NmYtYWEzMC1mOWI3MTFjMDI1MzcuanBnIiwid2lkdGgiOiI8PTEyODAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.oWJ-DNwTyINXvCERxN8t-etn8f63-0vuFM0F82OsnNY';

export const PRIME_NUMBERS = [
  2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71,
  73, 79, 83, 89, 97,
];
export const DEFAULT_HP = 35;
export const PARTIES_NAMES = [
  'Order of the Twilight Sentinels',
  'Circle of the Whispering Grove',
  'Brotherhood of the Crimson Eclipse',
  'Covenant of the Celestial Serpent',
  'League of the Ethereal Enclave',
  'Fellowship of the Astral Warden',
  'Alliance of the Sapphire Shroud',
  'Guild of the Everlasting Ember',
  'Conclave of the Verdant Vale',
  'Society of the Crimson Phoenix',
  'Legion of the Silent Star',
  'Circle of the Frozen Moon',
  'Covenant of the Iron Thistle',
  'Fellowship of the Eclipsed Sun',
  'Coalition of the Shadowed Peaks',
  'Order of the Maelstrom Templars',
  'League of the Whispering Sands',
  'Brotherhood of the Crystal Gaze',
  'Covenant of the Embered Sky',
  'Guild of the Eternal Echo',
];
export const USERS_NAMES = [
  'Alaric Shadowbane',
  'Seraphina Mistwood',
  'Thorne Ironheart',
  'Lyra Moonshadow',
  'Ragnar Stormbringer',
  'Elara Frostwind',
  'Draven Nightshade',
  'Aria Silverleaf',
  'Finnian Blackthorn',
  'Isolde Fireheart',
  'Orion Sunwalker',
  'Morrigan Swiftblade',
  'Thalia Starfall',
  'Lucian Darkmoon',
  'Selene Evergreen',
  'Kaelen Dragonblood',
  'Freya Ravenwing',
  'Asher Emberstorm',
  'Lysander Frostbeard',
  'Elowen Wildfire',
  'Gideon Shadowstorm',
  'Rowan Stormcloak',
  'Elysia Nightingale',
  'Magnus Stonewall',
  'Soraya Skywatcher',
  'Cedric Frostbourne',
  'Astrid Sunfire',
  'Finnegan Ironwood',
  'Callista Silvermoon',
  'Roran Thunderheart',
  'Lyanna Shadowdancer',
  'Thaddeus Stonehelm',
  'Evelina Swiftarrow',
  'Leander Moonblade',
  'Sienna Emberwind',
  'Dorian Frostfall',
  'Evelynn Starfire',
  'Ronan Shadowthorn',
  'Freyja Frostbloom',
  'Kieran Stormstride',
  'Alaric Grimwood',
  'Elara Nightwhisper',
  'Thorne Dragonbane',
  'Isolde Wintermoon',
  'Orion Swiftstrike',
  'Selene Frostgale',
  'Lucian Emberfall',
  'Aria Starlight',
  'Finnian Shadowcaster',
  'Seraphina Stormchaser',
];
